#!/bin/sh
# chkconfig: 345 80 20
# 345 - runs at level 3 4 5
# 80 - start sequence level S80
# 20 - stop sequence level S20
#
start() {
        nohup /opt/timed & # runs in the background
}
stop() {
       pkill timed # kill the process
}
case "$1" in
     start)
        start
     ;;
     stop)
        stop
     ;;
     *)
        echo $"Usage: $0 (start|stop)"
        RETVAL=1
esac
exit 0
